<!DOCTYPE html>
<html lang="pt-BR">

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet" />
    <title>Starter template Bootstrap 5.2.0!</title>
</head>

<body>
    <nav class="py-3 bg-info">
        <ul class="nav justify-content-center">
            <li class="nav-item">
                <a class="nav-link active fs-5" aria-current="page" href="#">Active</a>
            </li>
            <li class="nav-item">
                <a class="nav-link fs-5" href="#">Link</a>
            </li>
            <li class="nav-item">
                <a class="nav-link fs-5" href="#">Link</a>
            </li>
            <li class="nav-item">
                <a class="nav-link disabled fs-5">Disabled</a>
            </li>
        </ul>
    </nav>

    <div class="container col-4">
        <form action="" method="POST">
            <div class="mb-3">
                <label for="name" class="form-label">First Name</label>
                <input type="text" name="firstName" class="form-control" aria-describedby="emailHelp" required>
            </div>
            <div class="mb-3">
                <label for="name" class="form-label">Last Name</label>
                <input type="text"  name="lastName" class="form-control" id="lastName" aria-describedby="emailHelp" required>
            </div>
            <div class="mb-3">
                <label for="email" class="form-label">Email address</label>
                <input type="email" name="email" class="form-control" id="email" aria-describedby="emailHelp" required>
            </div>
            <div class="mb-3">
                <label for="password" class="form-label">Password</label>
                <input type="password" name="password" class="form-control" id="exampleInputPassword1" required>
            </div>
            <div class="mb-3 form-check">
                <select name="status" id="status">
                    <option value="1">Ative</option>
                    <option value="0">Inative</option>
                </select>
            </div>
            <button type="submit" class="btn btn-primary">Submit</button>
        </form>
    </div>

    <div class="alert alert-primary" role="alert">
        <?php
        var_dump($_POST);
        ?>
    </div>


    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.5/dist/umd/popper.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/js/bootstrap.min.js"></script>
</body>

</html>